//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : jt
//  @ File Name : searchController.java
//  @ Date : 2018/11/28 ������
//  @ Author : 
//
//



package com.jt.search.controller;


public class searchController {
	public com.jt.search.service.SearchService searchService;
	public int pageSize;
	public String search(String key) {
		return key;
	
	}
}
